#!/usr/bin/env bash
set -e

date -u

echo add nvim ppa
sudo add-apt-repository -y ppa:neovim-ppa/stable > /dev/null

mkdir -p ~/.local/bin
mkdir -p ~/.config

echo update and install
sudo apt update && sudo apt install gcc g++ make neovim unzip > /dev/null

echo configure neovim
git clone https://github.com/orzv/nvim.git ~/.config/nvim > /dev/null
