#!/bin/zsh

dotenv() {
  local file=.env
  if [[ -n "$1" ]]; then
    file="$1"
  fi
  if [[ -f `pwd`/$file ]]; then
    for var in $(cat `pwd`/$file | grep -v '^#' | xargs); do
      export $var
    done
  else
    echo "$file not found"
    return 1
  fi
}

dotenv "$@"
